import Header from "@/components/layout/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { getCustomServerComponentClient } from "@/server/supabase/server-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App With Supabase and Drizzle",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    data: { session },
  } = await getCustomServerComponentClient().auth.getSession();

  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col")}>
        <Header initialSession={session} />

        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
